#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/app"
OUTPUT_FILE="/tmp/kbo-fans-aws.env"
FORCE=false
GENERATE_PUSH_SYNC_SECRET=true
REPO="<owner/repo>"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/push-demo-env-bootstrap.sh [--output /tmp/kbo-fans-aws.env] [--repo owner/repo] [--force]

Options:
  --output <path>                  Write the local untracked env file here.
                                   Default: /tmp/kbo-fans-aws.env
  --repo <owner/repo>              GitHub repository to show in next commands.
  --force                          Overwrite an existing output file.
  --no-generate-push-sync-secret   Leave PUSH_SYNC_SECRET as a placeholder.

Purpose:
  Create a local push demo env starter file from repository defaults and
  detected Firebase client config files. This command does not call AWS,
  GitHub, Firebase, or Apple services, and it does not print secret values.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      if [[ -z "${2:-}" ]]; then
        echo "--output requires a path." >&2
        exit 2
      fi
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --repo)
      if [[ -z "${2:-}" ]]; then
        echo "--repo requires owner/repo." >&2
        exit 2
      fi
      REPO="$2"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    --no-generate-push-sync-secret)
      GENERATE_PUSH_SYNC_SECRET=false
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -e "$OUTPUT_FILE" && "$FORCE" != "true" ]]; then
  echo "Output file already exists: $OUTPUT_FILE" >&2
  echo "Pass --force to overwrite it." >&2
  exit 2
fi

plist_project_id() {
  local path="$1"
  [[ -f "$path" ]] || return 0
  python3 - "$path" <<'PY'
import plistlib
import sys

path = sys.argv[1]
try:
    with open(path, "rb") as file:
        print(plistlib.load(file).get("PROJECT_ID", ""))
except Exception:
    print("")
PY
}

json_project_id() {
  local path="$1"
  [[ -f "$path" ]] || return 0
  python3 - "$path" <<'PY'
import json
import sys

path = sys.argv[1]
try:
    with open(path, "r", encoding="utf-8") as file:
        print(json.load(file).get("project_info", {}).get("project_id", ""))
except Exception:
    print("")
PY
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi
  python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
}

write_export() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    printf 'export %s=\n' "$name" >>"$TMP_FILE"
  else
    printf 'export %s=%q\n' "$name" "$value" >>"$TMP_FILE"
  fi
}

write_section() {
  printf '\n# %s\n' "$1" >>"$TMP_FILE"
}

write_comment() {
  local text="$1"
  printf '# %s\n' "$text" >>"$TMP_FILE"
}

ios_config="$APP_DIR/ios/Runner/GoogleService-Info.plist"
android_config="$APP_DIR/android/app/google-services.json"
ios_project_id="$(plist_project_id "$ios_config")"
android_project_id="$(json_project_id "$android_config")"
firebase_project_id="${ios_project_id:-$android_project_id}"
if [[ -z "$firebase_project_id" ]]; then
  firebase_project_id="your-firebase-project-id"
fi

push_sync_secret="replace_with_64_hex_random_value_generated_by_openssl_rand_hex_32"
generated_push_sync_secret=false
if [[ "$GENERATE_PUSH_SYNC_SECRET" == "true" ]]; then
  push_sync_secret="$(generate_secret)"
  generated_push_sync_secret=true
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
TMP_FILE="$(mktemp "${OUTPUT_FILE}.tmp.XXXXXX")"
trap 'rm -f "$TMP_FILE"' EXIT
chmod 600 "$TMP_FILE"

cat >"$TMP_FILE" <<EOF
# Local push / Live Activity demo env.
# Do not commit this file.
# Generated by scripts/push-demo-env-bootstrap.sh.
#
# Fill the placeholders below, then upload GitHub Actions inputs with:
#   ./scripts/github-push-secrets.sh --env-file $OUTPUT_FILE --repo $REPO --apply
# Re-run setup status after each change:
#   ./scripts/push-demo-setup-status.sh --env-file $OUTPUT_FILE --repo $REPO
EOF

write_section "Region / stack names"
write_comment "Keep ap-northeast-2 unless the AWS stack is intentionally moved."
write_export AWS_REGION "ap-northeast-2"
write_export KBO_PUSH_STACK_NAME "kbo-fans-push-demo"
write_export KBO_STACK_NAME_PREFIX "kbo-fans"

write_section "Firebase client config files"
write_comment "Source: Firebase Console > Project settings > Your apps."
write_comment "Target: GitHub secrets IOS_GOOGLE_SERVICE_INFO_PLIST / ANDROID_GOOGLE_SERVICES_JSON."
if [[ -f "$ios_config" ]]; then
  write_export IOS_GOOGLE_SERVICE_INFO_PLIST_FILE "$ios_config"
else
  write_export IOS_GOOGLE_SERVICE_INFO_PLIST_FILE "/path/to/GoogleService-Info.plist"
fi
if [[ -f "$android_config" ]]; then
  write_export ANDROID_GOOGLE_SERVICES_JSON_FILE "$android_config"
else
  write_export ANDROID_GOOGLE_SERVICES_JSON_FILE "/path/to/google-services.json"
fi

write_section "Backend secret source files"
write_comment "Firebase Admin source: Firebase Console > Project settings > Service accounts > Generate new private key."
write_comment "APNs source: Apple Developer > Certificates, Identifiers & Profiles > Keys > Apple Push Notifications service."
write_comment "Target: GitHub secrets and AWS Secrets Manager; keep these as local file paths, not committed content."
write_export FIREBASE_SERVICE_ACCOUNT_FILE "/path/to/firebase-service-account.json"
write_export APNS_AUTH_KEY_FILE "/path/to/AuthKey_XXXXXXXXXX.p8"

write_section "Identifiers"
write_comment "FIREBASE_PROJECT_ID must match the Firebase client and Admin JSON project."
write_comment "APNS_KEY_ID is the Apple key id; APNS_TEAM_ID is the Apple Developer team id."
write_comment "Use APNS_USE_SANDBOX=false for TestFlight/App Store style production pushes."
write_export FIREBASE_PROJECT_ID "$firebase_project_id"
write_export APNS_KEY_ID "XXXXXXXXXX"
write_export APNS_TEAM_ID "XXXXXXXXXX"
write_export APNS_USE_SANDBOX "false"

write_section "Scheduler secret"
write_comment "Generated locally for the backend sync trigger. Rotate if it was exposed."
write_export PUSH_SYNC_SECRET "$push_sync_secret"

write_section "GitHub Actions AWS auth"
write_comment "Preferred: run aws-github-oidc-role.sh --update-env-file and upload AWS_ROLE_TO_ASSUME."
write_comment "Fallback: use AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY only if OIDC cannot be created."
write_export AWS_ROLE_TO_ASSUME "arn:aws:iam::123456789012:role/kbo-fans-github-actions"
write_export AWS_ACCESS_KEY_ID ""
write_export AWS_SECRET_ACCESS_KEY ""

write_section "AWS image / network / HTTPS"
write_comment "ECR repository stores the backend image used by the always-on API and sync worker."
write_comment "VPC/subnets are required by the CloudFormation ALB + ECS Fargate stack."
write_comment "Keep ENABLE_HTTPS=true for real iPhone/release use. Set false only for temporary HTTP-only AWS smoke deploys before a domain is ready."
write_export ECR_REPOSITORY_URI "123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/kbo-fans-backend"
write_export KBO_BACKEND_IMAGE_TAG "latest"
write_export CONTAINER_IMAGE_URI "123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/kbo-fans-backend:latest"
write_export ECS_TASK_EXECUTION_ROLE_ARN "arn:aws:iam::123456789012:role/kbo-fans-ecs-task-execution"
write_export ECS_TASK_ROLE_ARN "arn:aws:iam::123456789012:role/kbo-fans-ecs-task"
write_export EFS_FILE_SYSTEM_ID "fs-00000000000000000"
write_export VPC_ID "vpc-00000000000000000"
write_export PUBLIC_SUBNET_A_ID "subnet-00000000000000000"
write_export PUBLIC_SUBNET_B_ID "subnet-11111111111111111"
write_export ENABLE_HTTPS "true"
write_export API_DOMAIN_NAME ""
write_export ACM_CERTIFICATE_ARN "arn:aws:acm:ap-northeast-2:123456789012:certificate/00000000-0000-0000-0000-000000000000"

write_section "Generated by aws-push-secrets.sh after real secret files are ready"
write_comment "These ARNs are produced by aws-push-secrets.sh or by the full demo deploy script."
write_comment "Leave empty until the local secret files above contain real values."
write_export SECRET_ARN_FIREBASE_SERVICE_ACCOUNT_JSON ""
write_export SECRET_ARN_APNS_AUTH_KEY_P8 ""
write_export SECRET_ARN_PUSH_SYNC_SECRET ""

mv "$TMP_FILE" "$OUTPUT_FILE"
trap - EXIT
chmod 600 "$OUTPUT_FILE"

echo "push_demo_env_bootstrap=status=ok output=$OUTPUT_FILE"
if [[ -f "$ios_config" ]]; then
  echo "detected=iOS Firebase config"
else
  echo "missing=iOS Firebase config"
fi
if [[ -f "$android_config" ]]; then
  echo "detected=Android Firebase config"
else
  echo "missing=Android Firebase config"
fi
if [[ -n "$ios_project_id" && -n "$android_project_id" && "$ios_project_id" != "$android_project_id" ]]; then
  echo "warn: iOS Firebase project id and Android Firebase project id differ" >&2
fi
if [[ "$generated_push_sync_secret" == "true" ]]; then
  echo "generated=PUSH_SYNC_SECRET"
fi
echo "next_command: edit $OUTPUT_FILE and replace Firebase Admin, Apple, and AWS placeholders by following the inline comments"
echo "next_command: ./scripts/aws-github-oidc-role.sh --env-file $OUTPUT_FILE --repo $REPO --dry-run"
echo "next_command: ./scripts/push-demo-readiness-audit.sh --env-file $OUTPUT_FILE --repo $REPO"
